CREATE DATABASE DB_STYLUS;

USE DB_STYLUS;


-- PARTE DO ADMIN

CREATE TABLE TB_ADMIN (
    ID_ADMIN INT primary key auto_increment,
        DS_EMAIL    VARCHAR(50),
        DS_SENHA    VARCHAR(50)
);

-- TABELAS DE PRODUTO

CREATE TABLE TB_PRODUTO_GENERO(
    ID_PRODUTO_GENERO INT PRIMARY KEY AUTO_INCREMENT,
        DS_GENERO    VARCHAR(30)
);

CREATE TABLE TB_PRODUTO_MARCA(
    ID_PRODUTO_MARCA INT PRIMARY KEY AUTO_INCREMENT,
        NM_MARCA    VARCHAR(30)

);

CREATE TABLE TB_PRODUTO_TAMANHO(
    ID_PRODUTO_TAMANHO INT PRIMARY KEY AUTO_INCREMENT,
        DS_TAMANHO        INT

);


CREATE TABLE TB_PRODUTO(
    ID_PRODUTO INT PRIMARY KEY AUTO_INCREMENT,
    ID_PRODUTO_MARCA    	INT,
    ID_PRODUTO_GENERO  		INT,
        QTD_PRODUTO    		INT,
        NM_PRODUTO       	VARCHAR(50),
        VL_PRODUTO       	DECIMAL(10, 2),
        DS_LANCAMENTO   	boolean,
        NR_PRODUTO			INT,
        IMG_PRODUTO			VARCHAR(800),
    foreign key (ID_PRODUTO_GENERO) references TB_PRODUTO_GENERO (ID_PRODUTO_GENERO),
    foreign key (ID_PRODUTO_MARCA) references TB_PRODUTO_MARCA (ID_PRODUTO_MARCA)
   

);

-- TABELAS DE USUARIO 

CREATE TABLE TB_USUARIO(
    ID_USUARIO INT PRIMARY KEY AUTO_INCREMENT,
		NM_USUARIO			VARCHAR(50),
        DS_EMAIL		   	VARCHAR(50),
        DS_SENHA		   	VARCHAR(50),
		NR_CPF				VARCHAR(50),
		NR_CEP				VARCHAR(50),
        DS_NASCIMENTO		date
        
);


insert into TB_USUARIO( NM_USUARIO, DS_EMAIL, DS_SENHA, NR_CPF, NR_CEP, DS_NASCIMENTO	)
VALUES('Junior', 'junior@gmail.com', '1234', '111111','04849', '2004-10-10');

select * from TB_USUARIO;



create table TB_USUARIO_LOGIN (

	ID_USUARIO_LOGIN	INT PRIMARY KEY AUTO_INCREMENT,
    ID_USUARIO			INT,
	DS_EMAIL			VARCHAR(50),
	DS_SENHA			VARCHAR(50),
    FOREIGN KEY (ID_USUARIO)
    REFERENCES TB_USUARIO (ID_USUARIO)
    
);

-- LISTAR PRODUTOS

SELECT ID_PRODUTO			ID,
		TB_PRODUTO_MARCA.NM_MARCA,
        TB_PRODUTO_GENERO.DS_GENERO,
        QTD_PRODUTO    		QUANTIDADE,
        NM_PRODUTO       	NOME,
        VL_PRODUTO       	VALOR,
        DS_LANCAMENTO   	LANCAMENTO,
        NR_PRODUTO			NUMERO
	FROM TB_PRODUTO
    INNER JOIN TB_PRODUTO_MARCA
	ON TB_PRODUTO.ID_PRODUTO_MARCA=TB_PRODUTO_MARCA.ID_PRODUTO_MARCA
    INNER JOIN TB_PRODUTO_GENERO
	ON TB_PRODUTO.ID_PRODUTO_GENERO=TB_PRODUTO_GENERO.ID_PRODUTO_GENERO
	WHERE ID_PRODUTO = 3;

SELECT ID_PRODUTO			ID,
        TB_PRODUTO_MARCA.NM_MARCA,
        TB_PRODUTO_GENERO.DS_GENERO,
        QTD_PRODUTO    		QUANTIDADE,
        NM_PRODUTO       	NOME,
        VL_PRODUTO       	VALOR,
        DS_LANCAMENTO   	LANCAMENTO,
        NR_PRODUTO			NUMERO
    FROM TB_PRODUTO
    INNER JOIN TB_PRODUTO_MARCA
    ON TB_PRODUTO.ID_PRODUTO_MARCA=TB_PRODUTO_MARCA.ID_PRODUTO_MARCA
    INNER JOIN TB_PRODUTO_GENERO
    ON TB_PRODUTO.ID_PRODUTO_GENERO=TB_PRODUTO_GENERO.ID_PRODUTO_GENERO
    WHERE NM_PRODUTO like  '%a%';