CREATE DATABASE DB_STYLUS;

USE DB_STYLUS;

CREATE TABLE TB_ADMIN (
    ID_ADMIN INT primary key auto_increment,
        DS_EMAIL    VARCHAR(50),
        DS_SENHA    VARCHAR(50)
);

CREATE TABLE TB_PRODUTO_GENERO(
    ID_PRODUTO_GENERO INT PRIMARY KEY AUTO_INCREMENT,
        DS_GENERO    VARCHAR(30)
);

CREATE TABLE TB_PRODUTO_MARCA(
    ID_PRODUTO_MARCA INT PRIMARY KEY AUTO_INCREMENT,
        NM_MARCA    VARCHAR(30)

);

CREATE TABLE TB_PRODUTO_TAMANHO(
    ID_PRODUTO_TAMANHO INT PRIMARY KEY AUTO_INCREMENT,
        DS_TAMANHO        INT

);


CREATE TABLE TB_PRODUTO(
    ID_PRODUTO INT PRIMARY KEY AUTO_INCREMENT,
    ID_PRODUTO_MARCA    	INT,
    ID_PRODUTO_GENERO  		INT,
        QTD_PRODUTO    		INT,
        NM_PRODUTO       	VARCHAR(50),
        VL_PRODUTO       	DECIMAL(10, 2),
        DS_LANCAMENTO   	boolean,
        NR_PRODUTO			INT,
        IMG_PRODUTO			VARCHAR(800),
    foreign key (ID_PRODUTO_GENERO) references TB_PRODUTO_GENERO (ID_PRODUTO_GENERO),
    foreign key (ID_PRODUTO_MARCA) references TB_PRODUTO_MARCA (ID_PRODUTO_MARCA)
   

);

DROP TABLE TB_PRODUTO_MARCA;