INSERT INTO TB_ADMIN (DS_EMAIL, DS_SENHA)
VALUES('junior', '1234');


INSERT INTO TB_PRODUTO_MARCA(NM_MARCA)
VALUES('jordan');

INSERT INTO TB_PRODUTO_GENERO (DS_GENERO)
VALUES('feminino');


INSERT INTO TB_PRODUTO (ID_PRODUTO_MARCA,ID_PRODUTO_GENERO,NM_PRODUTO,QTD_PRODUTO, VL_PRODUTO, DS_LANCAMENTO, NR_PRODUTO, IMG_PRODUTO)
VALUES(2,2,'kkkkk', 50, 1000.99, true, 41, '');

INSERT INTO TB_USUARIO (NM_USUARIO, DS_EMAIL, DS_SENHA,NR_CPF,NR_CEP,DT_NASCIMENTO)
VALUES(1,'biel', 'gabriel@usu.com.br' ,'1234', '50786372819','04880215','11.01.2004');

select ID_USUARIO			ID,
		NM_USUARIO  		NOME,
		DS_EMAIL    		EMAIL
from 	TB_USUARIO
where 	DS_EMAIL			='gabriel@usu.com.br'
and 	DS_SENHA			='1234';

select ID_USUARIO			ID,
		NM_USUARIO  		NOME,
		DS_EMAIL    		EMAIL,
        DS_SENHA			SENHA,
        NR_CPF				CPF,
        NR_CEP				CEP,
        DT_NASCIMENTO		NASCIMENTO
FROM  TB_USUARIO;



insert into TB_USUARIO( NM_USUARIO, DS_EMAIL, DS_SENHA, NR_CPF, NR_CEP, DS_NASCIMENTO)
VALUES('Junior', 'junior@gmail.com', '1234', '111111','04849', '2004-10-10');

select * from TB_USUARIO;

INSERT INTO TB_PRODUTO_TAMANHO (DS_TAMANHO)
VALUES(41);

UPDATE TB_PRODUTO
		SET IMG_PRODUTO     = ''
WHERE  ID_PRODUTO			= 1;

select  * from TB_ADMIN; 

select  * from TB_PRODUTO_MARCA;


select * from TB_PRODUTO_GENERO;

select * from TB_PRODUTO;

select * from TB_PRODUTO_TAMANHO;
